import os


class Config(object):
    SQLALCHEMY_DATABASE_URI = 'sqlite:///db.sqlite3'
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SECRET_KEY = os.getenv('SECRET_KEY')
    MIN_ORIGINAL_LINK_LENGTH = 1
    MAX_ORIGINAL_LINK_LENGTH = 128
    MIN_CUSTOM_ID_LENGTH = 1
    MAX_CUSTOM_ID_LENGTH = 16
